render/shaders.py
Created folder for render-related code.
Classes for shader management were added:
-Shader, describing an OpenGL program object.
-ShaderManager, that can be used to load, compile
and link all shaders from specified directory.
=> Added shader management system

render/rtargets.py
Added RTargetManager class, which is able
to track textures used as render targets.
Allows reducing number of textures
by reusing some free targets with matching
formats and size.
=> Added render target management

render/meshes.py, render/textures.py
Added MeshManager and TextureManager.
TextureManager loads images from specified folder
by filename and creates OpenGL texture objects.
MeshManager loads Wavefront OBJ files and
creates vertex array and vertex buffer objects
to render loaded meshes.
=> Added meshes and textures management

gui.py, ui_descr.py
Added code for rendering buttons and sliders
able to handle user input. Also added ui
layouts for pause and main menu.
=> Added gui-related code and initial ui prototype

app_state.py, scene.py
Scene class added to load scenes from
JSON scene descriptions and render them.
Also added missing app_state.py used
by both gui and scene code to
store managers for all resources.
=> Added code to load and render scenes

__main__.py, shaders/blur.frag, shaders/blur.vert, shaders/blur_h.frag, shaders/blur_h.vert, shaders/blur_v.frag, shaders/blur_v.vert, shaders/button_background.frag, shaders/button_background.vert, shaders/mesh_render.frag, shaders/mesh_render.vert, shaders/resolve.frag, shaders/resolve.vert, shaders/shadows.frag, shaders/shadows.vert, shaders/ssao.frag, shaders/ssao.vert, shaders/tex_rect.frag, shaders/tex_rect.vert
Updated shaders required version to match
the OpenGL context version. Fixed reload
of shaders and scene in main.
=> Fix minor issues

__main__.py, assets/level.json, gameplay.py
Now level is loaded from JSON file.
Also several functions are replaced with
class, which stores ecs-related stuff inside.
=> Reworked gameplay code.

__main__.py, assets/level.json, physics/collision.py, physics/gravity.py, player.py
Previously values in pixels were used, so
the rendered gameplay part was different
depending on display resolution.
=> Reworked physics to normalized coordinates

__main__.py, death_manager.py, gameplay.py, scene.py, shaders/ssao.frag, shaders/tex_rect.vert, ui_descr.py
Added callbacks for gameplay code to count number of killed enemies and show the results screen when player dies. Also, fixed billboard rendering artifacts.
=> Fixed rendering for billboards and added results screen

PyPlatformGame/gravity_test.py
Implemented gravity unit testing
=> Implemented gravity unit testing

MANIFEST.in, dodo.py, setup.cfg
Now docs, readme etc are not included
into wheel package.
=> Fixed files included to build

PyPlatformGame/main.py, PyPlatformGame/scene.py
Added draw order for billboards support in scene.
Also, now camera follows the player.
=> Added camera tracking player and draw order

PyPlatformGame/scene.py, PyPlatformGame/shaders/billboard.frag, PyPlatformGame/shaders/billboard.vert
FIxed upside-down billboards and depth
test issues.
=> Fixed billboard render

PyPlatformGame/assets/level.json, PyPlatformGame/billboard_renderer.py, PyPlatformGame/enemy.py, PyPlatformGame/gameplay.py, PyPlatformGame/player.py
Added the ability to wobble character sprites in the game to imitate
movement. Also made a couple of code fixes.
=> Added wobble

.gitignore, PyPlatformGame/__init__.py, PyPlatformGame/__main__.py, PyPlatformGame/audiomanager.py, PyPlatformGame/billboard_renderer.py, PyPlatformGame/death_manager.py, PyPlatformGame/gameplay.py, PyPlatformGame/main.py, PyPlatformGame/scene.py, PyPlatformGame/ui_descr.py, PyPlatformGame/win_manager.py, dodo.py, po/en/LC_MESSAGES/PyPlatformGame.po, po/ru/LC_MESSAGES/PyPlatformGame.po, pylintrc
Fixed pylint and pydocstyle warnings. Now both checks are enabled by default for "doit" command. Also doneminor improvements for camera behaviour in game.
=> Pylint checks enabled and minor improvements

PyPlatformGame/assets/level.json, PyPlatformGame/camera.py, PyPlatformGame/player.py
Added full level to the game and made some changes to camera and jump height.
=> Full level and associated changes

PyPlatformGame/audiomanager.py, tests/__init__.py, tests/disjointed_hurtbox_test.py
- Disjointed hurtbox test implemented
- Fixes in tests/__init__.py 
- Audio volume for music is set to be 0.5 by default
=> Disjointed hurtbox test implemented + audio background volume fix

PyPlatformGame/singleton.py, docs/PyPlatformGame.rst
Fixed wrong format of docstrings (it broke sphinx docs build)
and changed modules list in docs to match the real one.
=> Update for documentation

PyPlatformGame/assets/scene.json, PyPlatformGame/gui.py, PyPlatformGame/main.py, PyPlatformGame/player.py, PyPlatformGame/renderer.py, PyPlatformGame/ui_descr.py, po/en/LC_MESSAGES/PyPlatformGame.po, po/ru/LC_MESSAGES/PyPlatformGame.po
Minor changes (mostly design of UI, scene, etc)
=> Minor updates

pyproject.toml, setup.cfg
=> Added missing dependency
